#K8s-Deployment. Ensure that deployments can be created successfully with the desired number of replicas, correct container images along with other important deployment parameters.
#Verify that rolling updates are performed without downtime, allowing users to access the application throughout the update process.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:1.23  # Use your desired image here
        ports:
        - containerPort: 80
