apiVersion: v1
kind: Pod
metadata:
  name: pod-with-hard-affinity
spec:
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:  #hard
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values: 
                    - ssd
  containers:
  - name: nginx-container
    image: nginx
    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


# Only scheduled on nodes with disktype=ssd. If no such node exists, it stays pending.
