apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "250m"
        memory: "128Mi"
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: NotIn  # this is use for to say pod not schedule on this node
                values: 
                  - ssd

# In node-anti-affinity-pod the pod is not scheduled on node which labels as ssd but it scheduled on another node