apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    name: backend
spec:
  nodeSelector:
    node: backend
  containers:
  - name: backend
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
