apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend
spec:
  nodeSelector:
    node: frontend
  containers:
  - name: frontend
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
