apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-pod
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - frontend
          topologyKey: "kubernetes.io/hostname"


# this is the pod-affinity 

#This pod uses pod affinity to ensure it is scheduled on the same node as a pod with the label app: frontend.