apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: demo
    environment: production
spec:
  containers:
  - name: nginx
    image: nginx:latest  # Fixed image name (avoid "nginx-latest")
    resources:
      requests:
        memory: "128Mi"  # Minimum memory guaranteed
        cpu: "250m"      # Minimum CPU guaranteed (0.25 CPU)
      limits:
        memory: "256Mi"  # Max memory allowed
        cpu: "500m"      # Max CPU allowed (0.5 CPU)