apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: demo          # Matches Pods with label "app: demo"
    environment: production # Matches Pods with label "environment: production"
  ports:
    - port: 80
      targetPort: 80  # Ensures traffic is routed to the container's port
  type: ClusterIP