apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  volumes: 
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080



# volumes: → Defines the storage volumes that the Pod will use.

# - name: secret-volume → Declares a volume named "secret-volume".

# secret: → Specifies that this volume is created from a Kubernetes Secret.

# secretName: my-secret → Refers to a Secret named "my-secret" that exists in the cluster.

# 🔹 Purpose: This mounts a Secret as a volume, making sensitive data (like passwords, API keys) available inside the container.





# volumeMounts: → Defines how the container uses volumes.

# - name: secret-volume → Refers to the "secret-volume" defined earlier.

# mountPath: /etc/secret → The volume will be mounted at /etc/secret inside the container.

# readOnly: true → Ensures that the container cannot modify the mounted Secret.

# 🔹 Purpose: The contents of the Secret "my-secret" will be available inside the container at /etc/secret